project:
  render:
    - "*.qmd"
    - "!ignored.md"
  type: website
  output-dir: docs

website:
  title: "lukas westphal"
  background: dark
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - setup_intro.qmd
  sidebar:
    style: docked
    search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



